-- Drop tables if they already exist
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE Employee CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Route CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE Itinerary CASCADE CONSTRAINTS';
    EXECUTE IMMEDIATE 'DROP TABLE ItineraryDetail CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/



CREATE TABLE Employee (
  EmployeeID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  EmployeeName VARCHAR2(100) NOT NULL,
  Position VARCHAR2(100) NOT NULL
);
/
CREATE TABLE Route (
  RouteID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  RouteName VARCHAR2(100) NOT NULL,
  SourceWarehouseID RAW(16) NOT NULL,
  DestinationWarehouseID RAW(16) NOT NULL,
  AssignedEmployeeID RAW(16) NOT NULL,
  PlannedDate DATE NOT NULL
);
/
CREATE TABLE Itinerary (
  ItineraryID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  OrderDetailID RAW(16) NOT NULL,
  CreatedByEmployeeID RAW(16) NOT NULL,
  CreationDate DATE NOT NULL
);
/

CREATE TABLE ItineraryDetail (
  ItineraryDetailID RAW(16) DEFAULT SYS_GUID() PRIMARY KEY,
  ItineraryID RAW(16) NOT NULL,
  FromWarehouseID RAW(16) NOT NULL,
  ToWarehouseID RAW(16) NOT NULL,
  DepartureDate DATE NOT NULL,
  ArrivalDate DATE NOT NULL,
  Cost NUMBER(10,2) NOT NULL,
  Distance NUMBER(10,2) NOT NULL,
  Time NUMBER(10,2) NOT NULL
);

/

SELECT * FROM ROUTE;
SELECT * FROM EMPLOYEE;
SELECT * FROM ITINERARY;
SELECT * FROM ITINERARYDETAIL;


COMMIT;