--EXAMPLE DATA -- WAREHOUSE DATABASE

USE DC_Warehouse;
GO

DELETE FROM Warehouse
DELETE FROM Vehicle
DELETE FROM Package
DELETE FROM PackageDetails
DELETE FROM PackageHistory

--WAREHOUSES

EXEC ADD_WAREHOUSE 'Warsaw', '456 Industrial Rd, Warsaw';
EXEC ADD_WAREHOUSE 'Lodz', '123 Piotrkowska St, Lódz';
EXEC ADD_WAREHOUSE 'Krakow', '789 Wielopole St, Krakow';
EXEC ADD_WAREHOUSE 'Gdansk', '101 Grunwaldzka Ave, Gdansk';
EXEC ADD_WAREHOUSE 'Torun', '202 Szosa Lubicka St, Torun';
EXEC ADD_WAREHOUSE 'Gdynia', '303 Swietojanska St, Gdynia';
EXEC ADD_WAREHOUSE 'Rzeszow', '404 Rejtana Ave, Rzeszow';

SELECT * FROM Warehouse

-- VEHICLES

EXEC ADD_VEHICLE '1'; --DODAÆ CONNECTA DO EMPLOYEE Z ORACLA
EXEC ADD_VEHICLE '2';
EXEC ADD_VEHICLE '3';
EXEC ADD_VEHICLE '4';
EXEC ADD_VEHICLE '5';

SELECT * FROM Vehicle

-- PACKAGES

EXEC ADD_PACKAGE '1','1','4',  'NORMAL', 'SMALL', '1.23';
EXEC ADD_PACKAGE '2','2','3', 'NORMAL', 'LARGE', '9.56';
EXEC ADD_PACKAGE '3', '2','5', 'NORMAL', 'MEDIUM', '3.25';
EXEC ADD_PACKAGE '1', '1','7', 'NORMAL', 'MEDIUM', '3.93';
EXEC ADD_PACKAGE '2', '3','1', 'NORMAL', 'SMALL', '2.49';

SELECT * FROM Package
SELECT * FROM PackageDetails
SELECT * FROM PackageHistory

EXEC MOVE_PACKAGE_TO_VEHICLE '1', '1'
EXEC MOVE_PACKAGE_TO_VEHICLE '2', '1'
EXEC MOVE_PACKAGE_TO_VEHICLE '3', '2'
EXEC MOVE_PACKAGE_TO_VEHICLE '4', '2'
EXEC MOVE_PACKAGE_TO_VEHICLE '5', '2'

SELECT * FROM VehicleInventory
SELECT * FROM Package

EXEC MOVE_PACKAGE_TO_WAREHOUSE '1'
EXEC MOVE_PACKAGE_TO_WAREHOUSE '2'
EXEC MOVE_PACKAGE_TO_WAREHOUSE '3'
EXEC MOVE_PACKAGE_TO_WAREHOUSE '4'
EXEC MOVE_PACKAGE_TO_WAREHOUSE '5'

SELECT * FROM VehicleInventory
SELECT * FROM Package
SELECT * FROM PackageHistory


EXEC DELIVER_PACKAGE 3;
EXEC PRINT_PACKAGE_HISTORY 20;

EXEC PRINT_PACKAGE_HISTORY '1';

